/*
 * H_Seven_Segment_CFG.h
 *
 *  Created on: Sep 6, 2024
 *      Author: Afrotto
 */

#ifndef HAL_H_SEVEN_SEGMENT_H_SEVEN_SEGMENT_CFG_H_
#define HAL_H_SEVEN_SEGMENT_H_SEVEN_SEGMENT_CFG_H_

#define SEVEN_SEG_PORT PORT_C

#define SEVEN_SEG_BCD_PORT_HIGH_NIBBLE PORT_C
#define SEVEN_SEG_BCD_PORT_LOW_NIBBLE PORT_C

#define SEVEN_SEG_BCD_PIN0 PIN0
#define SEVEN_SEG_BCD_PIN1 PIN1
#define SEVEN_SEG_BCD_PIN2 PIN2
#define SEVEN_SEG_BCD_PIN3 PIN3

#define SEVEN_SEG_BCD_LOW_NIBBLE
#define SEVEN_SEG_BCD_HIGH_NIBBLE

#define SEVEN_SEG_COMM_CATHODE
//#define SEVEN_SEG_COMM_ANODE

#endif /* HAL_H_SEVEN_SEGMENT_H_SEVEN_SEGMENT_CFG_H_ */
